dotenv: .env
networks:
  default: development
  mainnet-fork:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  kovan:
    weth_token: "0xF3A6679B266899042276804930B3bFBaf807F15b"
wallets:
  from_key: ${PRIVATE_KEY}
