dotenv: .env
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
    - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
    - '@aave=aave/protocol-v2@1.0.1'
networks:
  default: mainnet-fork
  mainnet-fork:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    dai_token: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    lending_pool_addresses_provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    dai_eth_price_feed: "0x773616e4d11a78f511299002da57a0a94577f1f4"
  kovan:
    weth_token: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
    dai_token: "0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD"
    lending_pool_addresses_provider: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
    dai_eth_price_feed: "0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541"
wallets:
  from_key: ${PRIVATE_KEY}
settings:
  gas_limit: "2074044"